### ISSUE TITLE
修改sqlmode失败---Unknown system variable 'NO_ZERO_IN_DATE'

### ISSUE THREAD

**Issue by shenguobin** [ixrjog/opscloud4#12]
[root@devops-test-03 opsCloud]# mysql -uopscloud -popscloud
Warning: Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 34
Server version: 5.6.43 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@global.sql_mode;
+--------------------------------------------+
| @@global.sql_mode                          |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)

mysql> set @@global.sql_mode=‘STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
ERROR 1193 (HY000): Unknown system variable 'NO_ZERO_IN_DATE'
mysql>

**Comment by ixrjog** [comment]
此错误可以忽略，因为sql是从阿里云RDS中导出的
