### ISSUE TITLE
Gitlab API 错误

### ISSUE THREAD

**Issue by ns500** [ixrjog/opscloud4#18]
ui点击git仓库，gitlab报错：
28-May-2019 15:36:41.362 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Spring-Dispatcher] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: http://gitlab.xxx.com:80/api/v4/projects/1/repository/tags?per_page=100] with root cause
 java.io.FileNotFoundException: http://gitlab.xxx.com:80/api/v4/projects/1/repository/tags?per_page=100
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:363)
        at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:38)
        at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:236)

gitlab version：11.0.3
Gitlab API version: v4
我用postman测试token可以正常返回project list。
postman get : http://gitlab.xxx.com/api/v4/projects?private_token=7y3y2b11e-7LB_o-C_Q8

**Comment by ns500** [comment]
感觉像是api地址错误，是不是还需要配置什么，我刚部署完毕，什么都没有设置。
除了ldap，其他基础依赖都部署了。

**Comment by ixrjog** [comment]
gitlab相关配置
# gitlab配置(必须支持v4版本的API)
gitlab.url=http://gitlab.ops.cn:80
gitlab.token={GITLAB-TOKEN}  # admin账户token

还有你看下服务的域名解析是否正常 nslookup gitlab.ops.cn

**Comment by ns500** [comment]
# gitlab配置(必须支持v4版本的API)
gitlab.url=http://gitlab.xxx.com:80
gitlab.token=7y3y2b11e-7LB_o-C_Q8
gitlab域名一直是内部在用的。

**Comment by ixrjog** [comment]
private <T> T parse(HttpURLConnection connection, Class<T> type, T instance) throws IOException {
        InputStreamReader reader = null;
        try {
            if (byte[].class == type) {
                return type.cast(IOUtils.toByteArray(wrapStream(connection, connection.getInputStream())));
            }
            
            reader = new InputStreamReader(wrapStream(connection, connection.getInputStream()), "UTF-8");
            String json = IOUtils.toString(reader);
            if (type != null && type == String.class) {
                return type.cast(json);
            }
            if (type != null && type != Void.class) {
                return GitlabAPI.MAPPER.readValue(json, type);
            } else if (instance != null) {
                return GitlabAPI.MAPPER.readerForUpdating(instance).readValue(json);
            } else {
                return null;
            }
        } catch (SSLHandshakeException e) {
            throw new SSLException("You can disable certificate checking by setting ignoreCertificateErrors " +
                    "on GitlabHTTPRequestor.", e);
        } finally {
            IOUtils.closeQuietly(reader);
        }
    }

这是363行代码at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:363)
            reader = new InputStreamReader(wrapStream(connection, connection.getInputStream()), "UTF-8");
请检查你的配置文件是否为utf8编码

**Comment by ns500** [comment]
我用vscode重新保存了一下，utf8编码，替换了服务器上的配置文件，tomcat日志没有报错，页面还是有下列错误。我在想是不是api版本有问题，这个uri，我用postman也是报404。
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.36 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - Request processing failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: http://gitlab.xxx.com:80/api/v4/projects/1/repository/tags?per_page=100</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Request processing failed; nested exception is

**Comment by ixrjog** [comment]
我的gitlab版本11.2.3 06cbee3
这个接口是查询projectId=1项目的tag
mysql表名oc_gitlab_project查看下是那个项目，然后看下tag名称是否有特殊字符

**Comment by ns500** [comment]
表里第一条是你的数据，我删除了现在有数据了，可是为啥只有8条啊，我gitlab里边有很多项目。

**Comment by ixrjog** [comment]
页面点同步然后看下日志，如果有错误数据就不会录入了

**Comment by ns500** [comment]
日志没有报任何错误，还是8条，我看看代码吧，感谢。
