### ISSUE TITLE
tomcat启动报错

### ISSUE THREAD

**Issue by lhadmin06** [ixrjog/opscloud4#19]
一个是sl4j 一个是jdbc链接 memery leak 大概就是 在注册的时候已经有一个注册了

**Comment by ixrjog** [comment]
你看下readme里的版本要求 ，gradle3.1/ jdk8/tomcat8.0.36

**Comment by lhadmin06** [comment]
org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

**Comment by lhadmin06** [comment]
jdk1.8和tomcat确实是8.0.36。

**Comment by lhadmin06** [comment]
> 你看下readme里的版本要求 ，gradle3.1/ jdk8/tomcat8.0.36

错误如图版本也是对的，

**Comment by lhadmin06** [comment]
> 你看下readme里的版本要求 ，gradle3.1/ jdk8/tomcat8.0.36

错误如图版本也是对的，

**Comment by ixrjog** [comment]
这不是致命错误，你看下ldap/mysql/redis是否配置正确

**Comment by lhadmin06** [comment]
我想问一下简单启动项目  只用mysql redis 和项目可以启动吗

**Comment by ixrjog** [comment]
可以启动，但配置文件的配置项不能删除

**Comment by lhadmin06** [comment]
> 可以启动，但配置文件的配置项不能删除

感谢您 我今天重新导入试一试，我先启动项目再去研究插件 谢谢 有问题再联系您 请问方便加QQ吗561810371

**Comment by ixrjog** [comment]
群号:630913972
