### ISSUE TITLE
web无法访问

### ISSUE THREAD

**Issue by NongCloud** [ixrjog/opscloud4#20]
安装好，tomcat正常启动，但是web却无法访问，netstat查看也有访问连接，3306，6379，8080这些服务端口都有连接，但web就是打不开网页？

**Comment by ixrjog** [comment]
1. 配置文件中mysql/redis是必须配置的，其它配置项不能注释掉
2. 看下tomcat日志

**Comment by NongCloud** [comment]
这个是我的配置 
【  jdbc_url=jdbc:mysql://192.168.33.20:3306/opscloud-pre?useUnicode=true&characterEncoding=utf8&autoReconnect=true
jdbc_user=opscloud
jdbc_password=opscloud
jumpserver_jdbc_url=jdbc:mysql://192.168.33.20:3306/jumpserver?useUnicode=true&characterEncoding=utf8&autoReconnect=true
jumpserver_jdbc_user=jms
jumpserver_jdbc_password=jms
jumpserver.host=https://jms.ops.cn
jumpserver.user=jms
jumpserver.passwd=jms
coco.host=oc.ops.cn
aliyun.access.key=AK
aliyun.access.secret=AC
aliyun.region.id=cn-hangzhou,cn-hongkong,us-west-1,cn-shanghai
aliyun.ecs.public.network.id=10
aliyun.ecs.classic.security.group.id=-
ldap.url=ldap://127.0.0.1:10389
ldap.base.dn=ou=system
ldap.manager.dn=uid=admin,ou=system
ldap.manager.passwd=secret
ldap.group.dn=ou=groups
ldap.user.dn=ou=users
ldap.user.id=cn
ldap.user.object=inetorgperson
ldap.group.object=groupOfUniqueNames
ldap.group.member=uniqueMember
invoke.env=online
redis.host=127.0.0.1
redis.port=6379
redis.pwd=
email.host=smtp.exmail.qq.com
email.user=ops@ops.com
email.passwd=opscloud
task.open=true
admin.passwd=opscloud
external.url=https://oc.ops.cn
keystore.filePath=/data/www/data/keystore/
ansible.bin=/usr/bin/ansible
ansible.playbook.bin=/usr/bin/ansible-playbook
ansible.scripts.path=/data/www/data/scrips
ansible.logs.path=/data/www/data/logs
ss.servers=hz-ss3.ops.cn:prod,hk-ss1.ops.cn:hongkong
gitlab.url=http://gitlab.ops.cn:80
gitlab.token=GITLAB_TOKEN
jenkins.url=http://ci.ops.cn
jenkins.user=admin
jenkins.token=JENKINS_TOKEN
dns.public.conf=/data/www/data/dnsmasq/dnsmasq-public.conf
dns.conf=/data/www/data/dnsmasq/dnsmasq.conf
zabbix.url=http://192.168.33.10/api_jsonrpc.php
zabbix.user=Admin
zabbix.passwd=zabbix
sonar.host=http://sonar.ops.cn
sonar.token=SONAR_TOKEN
vcsa.host=
vcsa.user=
vcsa.passwd=
gateway.admin.test.host=http://gateway-admin.test.ops.cn
gateway.admin.test.ak=AK
gateway.admin.pre.host=http://gateway-admin.test.ops.cn
gateway.admin.pre.ak=AK
gateway.admin.prod.host=http://gateway-admin.test.ops.cn
gateway.admin.prod.ak=AK
zookeeper.test.server=192.168.2.40:2181
dubbo.resolve.path=/data/www/data/dubbo-resolve】
现在是在自己的虚拟机中测试， 配置来连接mysql、redis，还有zabbix，ladp现在也是本机安装的。其他的功能我应该用不到，所以就没有配置了
这样配置后，web访问时访问不到页面！

**Comment by ixrjog** [comment]
需要看详细的日志，从上往下看
