### ISSUE TITLE
mvn 报错

### ISSUE THREAD

**Issue by Lee-Z** [ixrjog/opscloud4#27]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/ws/XtermWSController.java:[35,8] class XTermWSController is public, should be declared in a file named XTermWSController.java
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/ticket/impl/handler/TicketServerGroupHandler.java:[65,68] cannot find symbol
  symbol:   method getServerGroup()
  location: variable serverGroupEntry of type com.baiyi.opscloud.factory.ticket.entry.ServerGroupEntry
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/ticket/impl/handler/TicketServerGroupHandler.java:[70,72] cannot find symbol
  symbol:   method getNeedAdministratorAccount()
  location: variable serverGroupEntry of type com.baiyi.opscloud.factory.ticket.entry.ServerGroupEntry
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/change/consumer/impl/BaseServerChangeConsumer.java:[73,58] cannot find symbol
  symbol:   method getCode()
  location: variable changeResult of type com.baiyi.opscloud.factory.change.consumer.bo.ChangeResult
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/change/consumer/impl/BaseServerChangeConsumer.java:[74,57] cannot find symbol
  symbol:   method getMsg()
  location: variable changeResult of type com.baiyi.opscloud.factory.change.consumer.bo.ChangeResult
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/change/consumer/impl/BaseServerChangeConsumer.java:[82,54] cannot find symbol
  symbol:   method getCode()
  location: variable changeResult of type com.baiyi.opscloud.factory.change.consumer.bo.ChangeResult
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/change/consumer/impl/BaseServerChangeConsumer.java:[83,53] cannot find symbol
  symbol:   method getMsg()
  location: variable changeResult of type com.baiyi.opscloud.factory.change.consumer.bo.ChangeResult
[ERROR] /app/opsCloud-master/opscloud-manage/src/main/java/com/baiyi/opscloud/factory/change/consumer/impl/ApplicationStopConsumer.java:[64,53] cannot find symbol
  symbol:   method builder()

**Comment by ixrjog** [comment]
IDEA中安装lombok插件，代码中使用了@Builder&@Data注解

**Comment by Lee-Z** [comment]
已拉和你沟通，拉取最新的代码即可解决
