### ISSUE TITLE
项目停了？

### ISSUE THREAD

**Issue by berlinsaint** [ixrjog/opscloud4#34]
项目停了？

**Comment by ixrjog** [comment]
一直在开发中，只是没有提交github

**Comment by berlinsaint** [comment]
后续也不会提交更新了么。。。感觉好久 好久没有看到这个项目活跃了。。。。扫了下， 基本的python的运维平台比较火。。。java很少。。

**Comment by ixrjog** [comment]
opscloud已经比较稳定了，现在全部精力投入在caesar发布平台上
