### ISSUE TITLE
mvn时报错

### ISSUE THREAD

**Issue by Aiden-zyq** [ixrjog/opscloud4#38]
前面一切顺利，mvn时报如下错误，今天中午git拉取的
![1808f48c31a2d4fa77b7408df207eea436714667b3c7f65d36645f925a3ac818QzpcVXNlcnNcc20tMDAxMVxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNDIzNjc2OTAzX3YyXEltYWdlRmlsZXNcODdGNkY2MzctMDc2NS00NmRiLUEzMDEtOTk1OEZDRkUxMUVFLjM2MF90aHVtYg==](https://user-images.githubusercontent.com/39584794/120424955-f4404080-c39f-11eb-91aa-89054636d925.png)

**Comment by Aiden-zyq** [comment]
错误信息详情如下[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.527 s
[INFO] Finished at: 2021-06-02T12:39:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project opscloud-dingtalk: Could not resolve dependencies for project com.baiyi:opscloud-dingtalk:jar:0.0.1-SNAPSHOT: Could not find artifact com.dingtalk.api:taobao-sdk-java:jar:1.0.1-20201102.123754-1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :opscloud-dingtalk

**Comment by 370569218** [comment]
> 错误信息详情如下[INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 26.527 s
> [INFO] Finished at: 2021-06-02T12:39:13+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project opscloud-dingtalk: Could not resolve dependencies for project com.baiyi:opscloud-dingtalk:jar:0.0.1-SNAPSHOT: Could not find artifact com.dingtalk.api:taobao-sdk-java:jar:1.0.1-20201102.123754-1 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :opscloud-dingtalk

您好，这个问题你解决了吗
