### ISSUE TITLE
3.0.1的版本mvn构建的时候提示缺少jar包

### ISSUE THREAD

**Issue by 370569218** [ixrjog/opscloud4#43]
Failed to execute goal on project opscloud-dingtalk: Could not resolve dependencies for project com.baiyi:opscloud-dingtalk:jar:0.0.1-SNAPSHOT: Could not find artifact com.dingtalk.api:taobao-sdk-java:jar:1.0.1-20201102.123754-1 -> [Help 1]
![image](https://user-images.githubusercontent.com/23556204/125153369-ca8bed80-e185-11eb-909d-95fc08b2b4e5.png)

**Comment by ixrjog** [comment]
使用tag:3.0.0版本

**Comment by 370569218** [comment]
> 使用tag:3.0.0版本

您好tag3.0.0不支持腾讯云呀，我需要管理腾讯云服务器
