### ISSUE TITLE
关于4.0版本的一些问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [ixrjog/opscloud4#48]
我已经下载了4.0版本的前端项目和后端项目两个工程，并使用两个项目的默认分支，进行了打包运行。想请教如下问题：

在[功能介绍](https://www.kancloud.cn/ixrjog/opscloud4/2361886)部分下载sql是不是不太全？问题体现在：

- /api/auth/menu/query 这个接口访问的时候404
- /oc3路径需要修改为/api
- 登录后再去访问时，发现access_token表不存在，已经修改为user_api_token，但是access_token并未更新，也未看到有更新的逻辑

目前遇到了这几个问题，请指点迷津，感谢！

**Comment by ixrjog** [comment]
4.0版本前端仓库https://github.com/ixrjog/opscloud4-web，accessToken类似阿里与的AccessKey只用于外部平台接口调用
