### ISSUE TITLE
关于快速体验项目的建议

### ISSUE THREAD

**Issue by ChangJinLong** [ixrjog/opscloud4#49]
我已经下载了4.0.3版本的前端项目和后端项目两个工程，并使用两个项目的默认分支，并成功打包运行了，目前遇到了一个问题。

sql是不是不太全，问题体现在：当我用demo账户登录时提示我鉴权失败，后来我到数据库中看了一下权限相关的表，发现里面的数据都是空的。这就让人很难办，首先我不了解该项目表结构之间的关联关系，当然如果我查阅源码也是可以自己归发现的，但是那样很耗时的，对于想快速体验该项目的同学很不友好。

 ### **小建议**：
> 希望初始化数据中有一个admin账号，该账号包含了所有权限。

最后感谢分享！

**Comment by ixrjog** [comment]
感谢使用
建议使用Tag版本构建项目: 目前最新的tag=4.0.3(前后端)，sql在源码目录中有提供https://github.com/ixrjog/opscloud4/blob/master/resource/database/4.0.3/opscloud4_4.0.3.sql
你可以用我的账户（超级管理员）登录 username: baiyi   空密码

**Comment by ydq870102** [comment]
4.03的版本，用baiyi账号登录进去会提示鉴权失败，还需要增加哪些表数据？

**Comment by ixrjog** [comment]
在auth_user_role表中插入数据：username= baiyi , role_id = 1
 (role_id 对应 auth_role表主键)

**Comment by alanlvle** [comment]
![image](https://user-images.githubusercontent.com/25681693/146321533-07f3e155-8058-4b1d-9c6e-569d13ab4827.png)
加了之后还是报鉴权失败，还有哪里需要改的吗？ 谢谢！

**Comment by ixrjog** [comment]
浏览器打开看下哪个接口鉴权失败

**Comment by alanlvle** [comment]
拉下token，使用postman调用http://localhost:8080/api/user/ui/info/get报错
![image](https://user-images.githubusercontent.com/25681693/146322667-967b367a-7fc2-4834-a954-6697d6eef26f.png)

**Comment by alanlvle** [comment]
![image](https://user-images.githubusercontent.com/25681693/146323671-59e57100-26d2-48c8-a5ef-688c4f621858.png)

**Comment by ixrjog** [comment]
![image](https://user-images.githubusercontent.com/3479112/146323951-b663bed4-868e-4793-bd72-bbd1de100f07.png)
看下数据库是否有这条记录
select * from auth_resource where resource_name like '%info%'

**Comment by alanlvle** [comment]
有的。
![image](https://user-images.githubusercontent.com/25681693/146324537-4c2f2746-1548-4119-aa78-4983e3cacb94.png)

**Comment by alanlvle** [comment]
使用skywalking查看接口时正常的。
![image](https://user-images.githubusercontent.com/25681693/146324711-0642fa87-e30f-415a-ab5c-4d0f83f84f6e.png)

**Comment by ixrjog** [comment]
![image](https://user-images.githubusercontent.com/3479112/146325446-71ea83a0-e758-4639-9942-dab5485923c7.png)
AuthFilter类上打断点看下

**Comment by alanlvle** [comment]
可以了，我用的数据库时间时区不对，导致token验证不过。非常感谢！

**Comment by ixrjog** [comment]
感谢使用！
