### ISSUE TITLE
用的主分支，查询用户信息报错

### ISSUE THREAD

**Issue by alanlvle** [ixrjog/opscloud4#50]
![image](https://user-images.githubusercontent.com/25681693/146332221-3ed869a0-fb4c-4806-a313-69a688e926ec.png)
发现字段名称改了，是不是没有更新sql。
![image](https://user-images.githubusercontent.com/25681693/146332104-e2ca3104-a34c-490f-9349-5d572c091999.png)

**Comment by ixrjog** [comment]
不能直接使用branch版本，必须使用tag版本代码并对应tag版本sql
