### ISSUE TITLE
V4.0.4前端不能接入zabbix数据源

### ISSUE THREAD

**Issue by alanlvle** [ixrjog/opscloud4#51]
V4.0.4前端无法加zabbix

![image](https://user-images.githubusercontent.com/25681693/146894827-167c63c5-0e4e-447c-a582-6f18bd2162f4.png)
![image](https://user-images.githubusercontent.com/25681693/146894907-d7320fc6-888c-4147-9d9f-3abdbfe603a5.png)
看源码少了ZABBIX类型
![image](https://user-images.githubusercontent.com/25681693/146895051-055b33b5-cf96-448e-8c49-f370667ca74e.png)

**Comment by ixrjog** [comment]
新版本已增加，你要用的话可以通过数据库配置实例

**Comment by alanlvle** [comment]
https://github.com/ixrjog/opscloud4-web/blob/4.0.6/src/components/opscloud/datasource/DatasourceInstanceRegisterEditor.vue
使用新版本还是没有加

**Comment by ixrjog** [comment]
已提交https://github.com/ixrjog/opscloud4-web/commit/8e52049ac3170ec15da3cd1934f182f52e0599be
