### ISSUE TITLE
关于k8s的pod容器终端无法登录问题

### ISSUE THREAD

**Issue by Hison-y** [ixrjog/opscloud4#52]
登录容器终端的时候无法操作,感觉是没登录成功,而且后台没报错,有一些日志如下
新事件 Event success! message: SimpleEvent(eventType=USER_PERMISSION, action=CREATE, body=UserPermission(id=29047, userId=1, businessId=81, businessType=8, permissionRole=null, rate=null, content=null, createTime=null, updateTime=null))
2021-12-21 18:04:12.099  INFO 2924 --- [Async-Service-5] c.b.o.event.listener.NoticeListener      : 监听事件 : eventType = USER_PERMISSION , action = CREATE
![image](https://user-images.githubusercontent.com/33959959/146912604-b4b0f542-874f-4ddc-8a2d-aefd8f51fe68.png)
![image](https://user-images.githubusercontent.com/33959959/146912650-866046e2-28e7-42ff-a654-2a498f18b534.png)
我用的4.0.4后端的代码,后端也没报错所以不好排查,大佬能帮我看看怎么解决吗
还有就是应用配置里面的应用key是填什么的,是不是因为这里的原因
![image](https://user-images.githubusercontent.com/33959959/146912969-ce3005ea-e6ad-473c-8c0b-3414054c0c83.png)
而且终端操作页面跟你视频介绍的不一样,你视频里面的是图标我这里显示的是字母单词Terminal和Log,这两个操作看了前端请求的路径都是/api/ws/kubernetes/terminal,是不是这里的问题导致的,麻烦大佬解决这个问题,现在很需要这个功能,谢谢

**Comment by ixrjog** [comment]
请检查当前容器镜像是否支持终端登录，点击web中log看下是否有日志滚动

**Comment by Hison-y** [comment]
> 请检查当前容器镜像是否支持终端登录，点击web中log看下是否有日志滚动

怎么查看当前容器镜像是否支持终端登录,是我部署的那个应用的镜像是吗

**Comment by Hison-y** [comment]
> 请检查当前容器镜像是否支持终端登录，点击web中log看下是否有日志滚动

或者是有什么办法能设置我的容器镜像能支持终端登录,有文档吗,而且我看了我页面中Terminal和Log点击操作请求的路径都是/api/ws/kubernetes/terminal

**Comment by ixrjog** [comment]
日志能出来吗，如果你用的是阿里云ACK，控制台可以登录容器终端

**Comment by Hison-y** [comment]
> 日志能出来吗，如果你用的是阿里云ACK，控制台可以登录容器终端
浏览器控制台的报错信息
![image](https://user-images.githubusercontent.com/33959959/147018825-0b0910bf-b3fa-40e1-ae49-5f541754eea6.png)
阿里云ack我也接入过,在阿里云的控制台是可以登录终端,但是接入到ops系统也是无法登录,是不是我现在的系统版本这个功能还没支持,或者是我设置上哪里还有问题

**Comment by ixrjog** [comment]
nginx配置需要支持websocket协议
![image](https://user-images.githubusercontent.com/3479112/147020568-cf673d7f-a168-483e-964c-8149d3b6eb26.png)

**Comment by Hison-y** [comment]
> nginx配置需要支持websocket协议 ![image](https://user-images.githubusercontent.com/3479112/147020568-cf673d7f-a168-483e-964c-8149d3b6eb26.png)

我是本地分别部署的前端和后端,还没用ng进行代理的,而且也是本地浏览器直接请求的,是不是要将前端后端打包在一起部署起来然后用ng进行代理才能使用终端登录的功能

**Comment by ixrjog** [comment]
这种情况不需要配置，2种部署方式都支持web终端，你可以试下ssh-server是否能登录容器，oc4使用sh命令启动容器shell请确认是否支持sh命令

**Comment by Hison-y** [comment]
> 这种情况不需要配置，2种部署方式都支持web终端，你可以试下ssh-server是否能登录容器，oc4使用sh命令启动容器shell请确认是否支持sh命令

![image](https://user-images.githubusercontent.com/33959959/147026748-f0e45aba-945e-488b-ae97-7418a892835d.png)
远程服务器是可以登录的,就是pod终端无法登录,说明是我pod容器的问题了是吧

**Comment by ixrjog** [comment]
oc4登录容器只需要与k8s-master通信即可，目前看可能是你的容器不支持sh，你可以找个centos容器镜像测试下

**Comment by Hison-y** [comment]
> oc4登录容器只需要与k8s-master通信即可，目前看可能是你的容器不支持sh，你可以找个centos容器镜像测试下

感谢大佬的耐心回复,问题已经解决了哈,谢谢

**Comment by ixrjog** [comment]
是因为容器镜像不支持`sh`命令？
