### ISSUE TITLE
V4.0.4不支持AWS

### ISSUE THREAD

**Issue by alanlvle** [ixrjog/opscloud4#53]
@ixrjog 你好！在页面配置AWS报错，看代码没有放出来，现在还没有适配吗？
![image](https://user-images.githubusercontent.com/25681693/147429444-bdacb438-40a6-4729-a51f-27424638a377.png)
![image](https://user-images.githubusercontent.com/25681693/147429479-b1bb9701-556a-44b7-8fa7-4fbde2815b75.png)

![image](https://user-images.githubusercontent.com/25681693/147429405-8f14ac04-9b9e-46eb-8f24-643e7ca02fc1.png)

**Comment by ixrjog** [comment]
手上没有aws账户，暂时无法开发aws相关资产

发自我的iPhone

**Comment by alanlvle** [comment]
老师，我以为支持呢。
![image](https://user-images.githubusercontent.com/25681693/147430785-bd2732fb-ef48-4855-a059-da26f5d65a43.png)

**Comment by alanlvle** [comment]
后面有计划接入吗？

**Comment by alanlvle** [comment]
国际化用AWS的比较多。

**Comment by ixrjog** [comment]
有计划做全云接入，AWS，腾讯云，其他云

**Comment by alanlvle** [comment]
老师，计划什么时候可以接入AWS资源。

**Comment by ixrjog** [comment]
申请到AWS-AK就开发，预计2022Q1

**Comment by ixrjog** [comment]
已支持AWS EC2、IAM、SQS+SNS
