### ISSUE TITLE
资产订阅有用例吗？

### ISSUE THREAD

**Issue by alanlvle** [ixrjog/opscloud4#54]
看V4.0.4，资源只有ansible源，没有接入其他的源。手动改了前端，改了zabbix，剧本怎么配置呢？有用例吗？
![image](https://user-images.githubusercontent.com/25681693/147621706-c82bf579-63a2-4691-9224-b518d7158cb4.png)

**Comment by ixrjog** [comment]
![image](https://user-images.githubusercontent.com/3479112/147622036-c6543674-4cbb-46ee-8e4e-ce7883e2d6ca.png)
![image](https://user-images.githubusercontent.com/3479112/147622051-7bcc384a-597e-4ef1-a0cf-3674153966ef.png)

**Comment by alanlvle** [comment]
资产订阅这块特性不是很理解，我开始以为是对数据源实例组装查询用的。看剧本老师提供的截图好像是任务操作的剧本。

**Comment by ixrjog** [comment]
Ansible主机清单文件是资产（万物皆资产），服务器数据变更事件会会重新生成此资产，并推送到订阅此资产的服务器

**Comment by alanlvle** [comment]
了解了，谢谢。剧本是需要哪些前置条件才能用呢？用的哪个工具执行的？可以简单介绍下架构吗？ 非常感谢。

**Comment by ixrjog** [comment]
1.在opscloud服务器上安装ansible(playbook)
2.数据源实例中配置ansible实例（需要配置ssh凭据）
![image](https://user-images.githubusercontent.com/3479112/147625402-1e52b28f-75eb-43ff-b76e-02298cbdc6fe.png)
![image](https://user-images.githubusercontent.com/3479112/147625414-cad22ac2-7794-47bb-a255-7e082551acbe.png)

**Comment by alanlvle** [comment]
有基础环境docker镜像吗？我们现在都是使用k8s部署的。

**Comment by ixrjog** [comment]
没有你可以自己做docker镜像

**Comment by alanlvle** [comment]
我做了个基础镜像上传到dockerhub，支持java,ansible,skywalking,bash,基础环境可能不全，只测试了数据源ansible,zabbix,aliyun，gitlab,jenkins。
hub链接:
https://hub.docker.com/layers/alan20210608/java/alpine-glibc-java-ansible.0.1/images/sha256:cc985f0bf1e5605d37e356d74e6e611e509c5a97dcc3f2be82bce5036e4fc13b

使用dockerfile配置
`FROM gj-public-aws-harbor.zatech.com/sre/meta-iac:java-ansible-init.0.2

COPY ./opscloud-manage/target/opscloud-manage-iac.jar /root/startup/

WORKDIR /root/startup/

EXPOSE 9015

CMD ["java","-javaagent:/root/startup/skywalking-agent/skywalking-agent.jar","-Ddruid.mysql.usePingMethod=false","-Xms5120m","-Xmx5120m","-Xmn2048m","-Xss256k","-XX:MaxMetaspaceSize=256M","-XX:MetaspaceSize=256M","-XX:+DisableExplicitGC","-XX:+UseConcMarkSweepGC","-DAPP_DOMAIN=meta-iac","-jar", "opscloud-manage-iac.jar"]`

**Comment by ixrjog** [comment]
感谢测试！
新版本不需要手动传参-Ddruid.mysql.usePingMethod=false, 程序实现自动配置
