### ISSUE TITLE
默认用户名密码是什么

### ISSUE THREAD

**Issue by zhangsj** [ixrjog/opscloud4#57]
部署后用户名密码是什么

**Comment by ixrjog** [comment]
用户名 baiyi
密码 空
可查询user表

**Comment by zhangsj** [comment]
登进去提示鉴权失败，需要手动去数据库赋权吗

**Comment by ixrjog** [comment]
注意数据库版本8.0/时区UTC+8 Asia/Shanghai 
OpsCloud安装的版本？

**Comment by zhangsj** [comment]
时区是对的
版本是4.0.3

**Comment by ixrjog** [comment]
auth_user_role 表看下
![image](https://user-images.githubusercontent.com/3479112/150928050-6118138f-d63a-446e-ac9f-e06a846ab761.png)
把username改成你登录的账户

**Comment by zhangsj** [comment]
好了 登录进去了
