### ISSUE TITLE
部署时发现redis地址写死这个能配置吗，而且也发现注册失败，编译部署和下载jar试过都报错

### ISSUE THREAD

**Issue by AdminLei** [ixrjog/opscloud4#59]
![1647943782(1)](https://user-images.githubusercontent.com/39176720/159457597-619207be-ff18-4a18-9a5a-a635d03f0e38.png)

**Comment by ixrjog** [comment]
![image](https://user-images.githubusercontent.com/3479112/159459918-a9a895b0-caf5-45bb-8967-13c53d871a17.png)
配置文件中可以修改

**Comment by AdminLei** [comment]
我这边下载的代码没有dev这个yml只有prod的，并且已经改了，但是打包后启动还是会报错
![image](https://user-images.githubusercontent.com/39176720/159466127-71f39298-c422-47f3-8429-4f14f492930a.png)

**Comment by ixrjog** [comment]
# 项目支持多环境配置文件，通过-P ${env}  参数指定配置 application-${env}.yml
# e.g.  指定配置文件 application-prod.yml
$ mvn -Dmaven.test.skip=true clean package -P prod -U -am

**Comment by AdminLei** [comment]
我打包也是直接打包prod，并且打包后的classes里面的配置文件也是prod，但是启动还是报错云服务器的redis
![image](https://user-images.githubusercontent.com/39176720/159469306-61b97698-973f-4ee1-8892-3131bbaabd5e.png)

**Comment by ixrjog** [comment]
配置文件和日志截图给我看下

**Comment by AdminLei** [comment]
配置文件
![image](https://user-images.githubusercontent.com/39176720/159469515-76b80908-4dde-43c5-945f-ade43549d8a7.png)
![image](https://user-images.githubusercontent.com/39176720/159469562-c827d052-4db2-4bf3-9497-04e0b5ba15b6.png)

**Comment by AdminLei** [comment]
方便加个联系方式吗，我qq791424397

**Comment by ixrjog** [comment]
密码明文不能使用ENC()包裹，直接写；
ENC()表示使用密钥加密后的密文

**Comment by AdminLei** [comment]
但是ip没有读取对

**Comment by AdminLei** [comment]
谢谢 我改了在试试

**Comment by AdminLei** [comment]
你好我这边启动成功8080端口也已经开放但是还是浏览器访问不了，是有什么contextpath吗
![image](https://user-images.githubusercontent.com/39176720/159472866-51a5255a-ea78-42fe-ac1c-5eac9852d095.png)
![image](https://user-images.githubusercontent.com/39176720/159472893-05f6da39-6ec8-4afa-a954-54e094b5aea8.png)

**Comment by ixrjog** [comment]
这个项目是前后端分离的，只测试后端可以打开API文档地址 http://127.0.0.1:8080/doc.html#/home

**Comment by AdminLei** [comment]
前端有部署文档吗

**Comment by ixrjog** [comment]
本地调试：安装WebStorm直接启动项目即可

**Comment by AdminLei** [comment]
我在服务器上面打包的，需要修改后端的连接地址吗

**Comment by ixrjog** [comment]
~~~
# 前端打包命令
$ npm i
$ npm run build:prod
~~~

**Comment by AdminLei** [comment]
不需要配置后端服务地址吗

**Comment by ixrjog** [comment]
前端也是多环境的，开发环境配置文件.env.development，生产环境.env.prod
![image](https://user-images.githubusercontent.com/3479112/159476339-f88ce367-f5af-477b-8d93-dc4bbea19505.png)

**Comment by AdminLei** [comment]
这个没看见配置服务端地址的地方

**Comment by ixrjog** [comment]
prod 是相对路径访问，因为前后端使用nginx聚合了； dev环境是通过ip+端口访问服务端的

**Comment by AdminLei** [comment]
prod还需要nginx单独发布吗

**Comment by ixrjog** [comment]
前端编译文件放到static目录下，不需要nginx
![image](https://user-images.githubusercontent.com/3479112/159478165-be44efc2-2826-468f-930c-550ed29383d1.png)

**Comment by AdminLei** [comment]
我放了，但是界面怎么访问呢

**Comment by ixrjog** [comment]
127.0.0.1:8080/

**Comment by AdminLei** [comment]
![image](https://user-images.githubusercontent.com/39176720/159480047-5a0ba8b1-1283-422b-aa52-2580c00c8e06.png)
这个密码怎么为空。前端登录不了

**Comment by AdminLei** [comment]
而且控制台报了很多错误
![image](https://user-images.githubusercontent.com/39176720/159480216-5c1a59ef-3d4d-4557-96dd-7709d9b25597.png)

**Comment by ixrjog** [comment]
这个错误可以忽略，你查看user表找到可以登录的用户，把password字段置空，然后用空密码登录即可

**Comment by ixrjog** [comment]
最近增加了MFA功能，所以修改了user表结构，你可以参考修改
~~~
CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名',
  `uuid` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '前端框架用户UUID',
  `password` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '姓名',
  `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '显示名称',
  `email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '邮箱',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '有效',
  `last_login` timestamp NULL DEFAULT NULL,
  `wechat` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '手机',
  `mfa` tinyint(1) DEFAULT '0' COMMENT '启用MFA',
  `force_mfa` tinyint(1) DEFAULT '0' COMMENT '强制启用MFA',
  `created_by` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `source` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '数据源',
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `username` (`username`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=197 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='oc用户本地用户';
~~~

**Comment by AdminLei** [comment]
![image](https://user-images.githubusercontent.com/39176720/159480766-1d5ee106-8b8a-4911-9940-1b5a19e5ada5.png)
这个是啥意思

**Comment by ixrjog** [comment]
有问题明天再说吧，我下班了

**Comment by AdminLei** [comment]
好的

**Comment by AdminLei** [comment]
你好我这边部署还是有问题，有办法帮我解决下吗

**Comment by ixrjog** [comment]
请提出你的问题

**Comment by AdminLei** [comment]
我又重新按照你给的这个前端打了个prod包，我重新部署发现页面都没有了
![image](https://user-images.githubusercontent.com/39176720/159615573-c07f1c16-b121-4caf-90cc-f3b1d1089350.png)
按f12出现的这样的报错
![image](https://user-images.githubusercontent.com/39176720/159615612-81b11bb0-a428-4224-bd16-68c62d777876.png)

**Comment by ixrjog** [comment]
WebStorm启动项目看下，不应该有这个错误
![image](https://user-images.githubusercontent.com/3479112/159616015-b70bf818-2bd4-4f8b-ac7d-b3da313f0620.png)

**Comment by AdminLei** [comment]
那我去下载一个

**Comment by AdminLei** [comment]
![image](https://user-images.githubusercontent.com/39176720/159620446-96f3e56b-4929-4eda-9def-ea8dff0cbb69.png)
这边打包怎么失败了呢，run build可以 run build：prod不行

**Comment by AdminLei** [comment]
我run build 能打包这样可以用吗
![image](https://user-images.githubusercontent.com/39176720/159620546-4fcfc3cb-4221-414f-b5ce-dd7842ecd84e.png)

**Comment by AdminLei** [comment]
你那边能打个前端的prod的release包吗，我用你那个也行

**Comment by ixrjog** [comment]
前端可以用master分支试下

**Comment by AdminLei** [comment]
试过 打包都失败了

**Comment by ixrjog** [comment]
这是d2admin帮助文档： https://d2.pub/zh/doc/d2-admin/learn/start.html#%E5%AE%89%E8%A3%85%E7%8E%AF%E5%A2%83

**Comment by AdminLei** [comment]
你好 能release一个prod的安装包吗

**Comment by AdminLei** [comment]
我用你官网的prod包使用这个命令启动java -Xms5120m -Xmx5120m -Xmn2048m -Xss256k -XX:MaxMetaspaceSize=512M -XX:MetaspaceSize=256M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -Dspring.redis.host=127.0.0.1 -Dspring.redis.password=123456 -Dspring.datasource.druid.opscloud.username=opscloud4-prod -Dspring.datasource.druid.opscloud.password=rj6FaDKJFPTcbXDB -Dserver.port=8080 -jar opscloud-manage-prod.jar

在初始化redis这里就不动了，进程还在，没有其他的log打出来 ，我用ss -tnlp|grep 8080显示没有监听这是怎么回事
![image](https://user-images.githubusercontent.com/39176720/160798516-d5167e96-48ff-4a4a-ba3b-8bb975dd6965.png)
![image](https://user-images.githubusercontent.com/39176720/160798563-af04b5ef-c675-48eb-8a57-a9ed93761260.png)

**Comment by ixrjog** [comment]
校验Redis和校验Mysql
![image](https://user-images.githubusercontent.com/3479112/160799562-f4ddc551-dd89-497e-9045-e845065a61c5.png)

**Comment by AdminLei** [comment]
已经启动成功了 但是登陆显示服务器内部错误，这个在哪儿有log可以查询吗
![image](https://user-images.githubusercontent.com/39176720/160802503-a637ea5a-a708-41e0-8227-bf90dd19047c.png)

**Comment by AdminLei** [comment]
这里我看到了log 这个能看出是什么问题吗
![image](https://user-images.githubusercontent.com/39176720/160803109-d1d1d086-b836-4f2b-847a-fb03b9201eed.png)

**Comment by ixrjog** [comment]
敏感数据都使用了加密，所以你需要配置一个加密的盐

![image](https://user-images.githubusercontent.com/3479112/160803803-3841eb2a-0377-4b48-871b-07aecbbc1691.png)

方案1: 此处添加一个密码
~~~
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: 'org.jasypt.iv.NoIvGenerator'
    password: XXXXXXXXXXX
~~~

方案2:  增加启动参数
~~~
java -jar -Djasypt.encryptor.password=XXXXXXXXXX
~~~

**Comment by AdminLei** [comment]
这个是初始密码吗还是什么

**Comment by AdminLei** [comment]
我登录的时候输入1提示加密解密失败但是我数据库里面就是1，密码你做了加密吗
![image](https://user-images.githubusercontent.com/39176720/160805349-798a9998-20a8-4eab-93b2-79b181052600.png)

**Comment by ixrjog** [comment]
靠谱的我怎么会明文存储密码，所有敏感数据都会加密存储

**Comment by AdminLei** [comment]
用的32位大写还是小写 我转一下

**Comment by AdminLei** [comment]
是md5吗

**Comment by AdminLei** [comment]
我改成md5 32位小写还是密码错误
![image](https://user-images.githubusercontent.com/39176720/160807063-c5b217ac-9648-4579-8a0a-51655d7e4eb6.png)
![image](https://user-images.githubusercontent.com/39176720/160807083-fe7deea7-e92a-4330-96a6-7f25bf09bbee.png)

**Comment by ixrjog** [comment]
删除password字段内容即可用空密码登录，加密用的是PBEWithMD5AndDES算法，登录系统后可以修改账户密码
