### ISSUE TITLE
创建用户或者凭证报的加密错误，请问这个要怎么处理

### ISSUE THREAD

**Issue by unixtommy** [ixrjog/opscloud4#60]
ERROR 3494 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: either 'jasypt.encryptor.password', one of ['jasypt.encryptor.private-key-string', 'jasypt.encryptor.private-key-location'] for asymmetric encryption, or one of ['jasypt.encryptor.gcm-secret-key-string', 'jasypt.encryptor.gcm-secret-key-location', 'jasypt.encryptor.gcm-secret-key-password'] for AES/GCM encryption must be provided for Password-based or Asymmetric encryption] with root cause

**Comment by ixrjog** [comment]
这可能是2个问题造成的：
1. 未指定opscloud全局加密密钥  jasypt.encryptor.password=XXXXX
2. 新版本增加了MFA功能，user表增加了2个字段 mfa、force_mfa
~~~
CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名',
  `uuid` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '前端框架用户UUID',
  `password` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '姓名',
  `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '显示名称',
  `email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '邮箱',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '有效',
  `last_login` timestamp NULL DEFAULT NULL,
  `wechat` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '手机',
  `mfa` tinyint(1) DEFAULT '0' COMMENT '启用MFA',
  `force_mfa` tinyint(1) DEFAULT '0' COMMENT '强制启用MFA',
  `created_by` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `source` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '数据源',
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `username` (`username`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=207 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='oc用户本地用户';
~~~

**Comment by unixtommy** [comment]
1. jasypt.encryptor.password=XXXXX,这个是要在application-prod.xml里添加呢还是 启动的时候直接在启动参数里， 里面这个XXX是随便填写嘛
2. 安装文档提供的前后端融合的jar是不是跟当前仓库master不对应?

**Comment by unixtommy** [comment]
java -Xms2048m -Xmx2048m -Xmn2048m -Xss256k -XX:MaxMetaspaceSize=256M -XX:MetaspaceSize=256M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -Dspring.redis.password=123..abc -Dspring.datasource.druid.opscloud.username=root -Dspring.datasource.druid.opscloud.password=Hylinkad@123 -Dserver.port=8080  -Djasypt.encryptor.password="123456"  -jar ./opscloud-manage-prod.jar  我这样解决了 加密的问题。

**Comment by unixtommy** [comment]
就剩下https://opscloud4-res.oss-cn-hangzhou.aliyuncs.com/releases/4.0.8/opscloud-manage-prod.jar 这个jar是哪个分支编译出来的? 我编译了当前master的代码提示数据库很多字段的问题

**Comment by ixrjog** [comment]
1. java -jar -Djasypt.encryptor.password='XXXX' 优先级高于 application-prod.yml，2选1配置即可；
密钥可以用任意高强度随机字符串，例如
-
Djasypt.encryptor.password='KlSCi7bsruWscXk6XGuub41qcnHozbWYUvrLl2p7TnLU45DaUhXKBTJlLzo3dnk0WuYav17GEri2nVRbdSwS3wHTMyVxh4'

2. 文档jar和TAG对应，使用最新版本可以用源码自己构建

3. master分支为最新版本，数据库有改动可以自己看xml修改
![image](https://user-images.githubusercontent.com/3479112/161002561-d5aa281b-94ae-4cf4-8e8c-926e5c53a61b.png)

**Comment by unixtommy** [comment]
好的，多谢指点
