### ISSUE TITLE
前端工程

### ISSUE THREAD

**Issue by 28-datry** [ixrjog/opscloud4#67]
麻烦问一下，前端工程不开源么。

**Comment by ixrjog** [comment]
![image](https://user-images.githubusercontent.com/3479112/182081154-bb6e5bb9-68a1-4735-bbf0-24ae90eb665a.png)

**Comment by 28-datry** [comment]
访问地址404

**Comment by ixrjog** [comment]
https://github.com/ixrjog/opscloud4-web
