### ISSUE TITLE
大佬好，角色权限这块数据库的数据是清理了一些吗

### ISSUE THREAD

**Issue by cs81** [ixrjog/opscloud4#69]
![image](https://user-images.githubusercontent.com/52037441/187166698-fcccf650-606c-4794-b4fd-74488e235097.png)
大佬好，角色权限这块数据库的数据是清理了一些吗？添加新用户之后，使用新用户登录有很多权限方面的报错。。

**Comment by ixrjog** [comment]
没有提交新的RBAC配置

**Comment by cs81** [comment]
> 没有提交新的RBAC配置

哦，我添加一个新用户，并授予ops权限，然后不能访问侧边栏也是因为这个原因吗？

**Comment by ixrjog** [comment]
给用户授权base角色，ops菜单可以在下图配置
![image](https://user-images.githubusercontent.com/3479112/187168246-ee1c1eb2-f3ad-44f8-8f67-32bca2f37918.png)

**Comment by cs81** [comment]
> 给用户授权base角色，ops菜单可以在下图配置 ![image](https://user-images.githubusercontent.com/3479112/187168246-ee1c1eb2-f3ad-44f8-8f67-32bca2f37918.png)

![image](https://user-images.githubusercontent.com/52037441/187168812-1f81043c-5b68-45f3-b70b-6a30f18a6aef.png)
我授予了base和ops，然后也配置了base和ops能展示的菜单，登录进去还是报错。。我是在用户管理里面添加的用户

**Comment by ixrjog** [comment]
base角色绑定的资源部正确
![image](https://user-images.githubusercontent.com/3479112/187170569-b8380d57-2b2c-47bf-8a2a-a0ddfcbbf790.png)

**Comment by cs81** [comment]
![image](https://user-images.githubusercontent.com/52037441/187172509-3ea60507-7fd5-444c-8dff-ed73afe0a4b8.png)
鉴权失败的是这个接口，但是配置中好像没有这个接口
![image](https://user-images.githubusercontent.com/52037441/187172254-2fe3506f-86e3-4d7e-a4c0-060375d2128a.png)
![image](https://user-images.githubusercontent.com/52037441/187172367-828719bb-06a0-49da-badf-23c860647fc8.png)

**Comment by cs81** [comment]
![image](https://user-images.githubusercontent.com/52037441/187173783-dd114b02-4413-4814-9301-fe384ffac6bf.png)
我把base和ops所有的权限都勾选了，登录后还是查看不了

**Comment by cs81** [comment]
我的问题。。。。没配置对，需要把权限一个个加进去。。

**Comment by cs81** [comment]
感谢大佬解惑！！
