### ISSUE TITLE
前端登录otp access code怎么配置

### ISSUE THREAD

**Issue by acheng-floyd** [ixrjog/opscloud4#70]
部署完之后，默认登录账号密码是什么，以及otp access code是在哪配置？
![image](https://user-images.githubusercontent.com/62228888/189618729-19feee04-3603-43d1-865e-740bae740d7e.png)

**Comment by ixrjog** [comment]
1. 登录账户看user表中的username字段，password字段为空则使用空密码登录
2.用户没有启用MFA则不需要填写otp, 用户登录后在下图会有otp qrcode
![image](https://user-images.githubusercontent.com/3479112/189790989-b5254f34-c26b-4025-a193-e9646b963cac.png)
