### ISSUE TITLE
您好，方便更新下前端工程吗，现在仓库中的前端工程和后端工程严重不匹配

### ISSUE THREAD

**Issue by yangrui01** [ixrjog/opscloud4#74]

**Comment by ixrjog** [comment]
目前开源的版本为4.2.0，前后端版本应该是一致的

**Comment by yangrui01** [comment]
> 目前开源的版本为4.2.0，前后端版本应该是一致的

是一 致的，我搞错了，不好意思哈。咱们系统设计的应该是比较通用的，对很多资源都进行了抽象，用起来感觉配置分散在不同的地方，有些不知道怎么用，没有串起来，比如：leo模版、持续集成那块，有系统相关概念、操作的介绍吗，

**Comment by ixrjog** [comment]
平台集成了运维自动化的3个核心能力：统一账户全生命周期管理、持续交付、堡垒机；服务端对数据源资产做了抽象，可以快速接入研发域各种工具平台+各种云，并实现多实例管理；会Java可以从源码入手了解平台的设计

**Comment by yuanyuanzi1** [comment]
> 目前开源的版本为4.2.0，前后端版本应该是一致的

我咋没找到开源的版本为4.2.0前后端，是在哪里找呀，版本我看着是从4.0.9到4.3在到4.5呀
![image](https://github.com/ixrjog/opscloud4/assets/89431578/d80f6c4d-aad8-47b9-80a1-2f3b152bfbfa)

**Comment by ixrjog** [comment]
迭代太快，你可以用tag 4.5.0；前后端代码+SQL都有

**Comment by Yiipanny** [comment]
> 迭代太快，你可以用tag 4.5.0；前后端代码+SQL都有

我部署了最新的前后端master分支，发现提供的SQL 有很多缺失，audit_api 表没有，leo_deploy 里也缺字段，请问这是4.5.0版本的吗？

**Comment by ixrjog** [comment]
你要用tag 4.5.0的代码+4.5.0sql； 4.6.0（springboot+jdk21）的sql还没提交
